name: update-readme

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bibtexparser --pre
      - name: Run the script
        run: python make.py
      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "nicolasloizeau@gmail.com"
          git config --global user.name "nicolasloizeau"
          git add -A
          git commit -m "make readme.md" || exit 0
          git push
